# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-17 13:36
from __future__ import unicode_literals

import decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.CharField(max_length=200)),
                ('millage', models.CharField(max_length=7)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=4, verbose_name=decimal.Decimal)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
